FROM  python:3.9.16-alpine as build

WORKDIR /data

COPY . .

RUN pip install -r requirements.txt

RUN mkdocs build

FROM python:3.9.16-alpine

WORKDIR /data

COPY --from=build /data/site .


EXPOSE 8000

CMD  python -m http.server 8000